In [1]:
import numpy as np

In [2]:
# creating single dimension array
a=np.array([1,34,56,65,4])

In [3]:
# another 1-D array
b=np.array([2,34,56,23,4])

In [4]:
a

array([ 1, 34, 56, 65,  4])

In [5]:
b

array([ 2, 34, 56, 23,  4])

In [6]:
a+b

array([  3,  68, 112,  88,   8])

In [9]:
# creating 2-D array
x=np.array([[2,90],[78,5],[3,4],[24,56]])

In [10]:
x

array([[ 2, 90],
       [78,  5],
       [ 3,  4],
       [24, 56]])

In [11]:
x[0][1]

90

In [12]:
x[0,1]

90

In [13]:
x+3

array([[ 5, 93],
       [81,  8],
       [ 6,  7],
       [27, 59]])

In [14]:
x^2


array([[ 0, 88],
       [76,  7],
       [ 1,  6],
       [26, 58]])

In [15]:
x**2

array([[   4, 8100],
       [6084,   25],
       [   9,   16],
       [ 576, 3136]])

In [17]:
x[0,1],x[2,1]


(90, 4)

In [19]:
# dimension
x.shape

(4, 2)

In [24]:
y=x.reshape(2,4)

In [25]:
x

array([[ 2, 90],
       [78,  5],
       [ 3,  4],
       [24, 56]])

In [26]:
y

array([[ 2, 90, 78,  5],
       [ 3,  4, 24, 56]])

In [27]:
y[0]

array([ 2, 90, 78,  5])

In [28]:
# only columns
y[0:,2]

array([78, 24])

In [29]:
y[:,1]

array([90,  4])

In [31]:
y[0:,0]

array([2, 3])

In [32]:
y[0:,2:]

array([[78,  5],
       [24, 56]])

In [34]:
y[0:,1:3]

array([[90, 78],
       [ 4, 24]])

In [37]:
zr=np.zeros((5,5))

In [38]:
zr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.full((4,6),6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [41]:
# to get the o/p in integer form
np.ones((4,4),dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)